version: 0.0
os: linux
files:
  - source: /
    destination: /var/www/html
hooks:
  AfterInstall:
    - location: install.sh
      runas: root
  ApplicationStart:
    - location: applicationStart.sh
      runas: root