version: 0.2

phases:
  install:
    runtime-versions:
        php: 7.4
    commands:
      - curl -sS https://getcomposer.org/installer | php
      - mv composer.phar /usr/local/bin/composer
      - composer install --no-interaction

artifacts:
  files:
    - '**/*'
  name: CodeigniterTest